### ISSUE TITLE
DST Switchover Behavior

### ISSUE THREAD

**Issue by sherson** [umts/BusInfoBoard#9]
I emailed Avail about this last week, and this morning I was informed they're looking into it. Issue created since this is coming up in 12 days (I'll update it with what Avail comes back with):

> How do the Avail realtime feed and bus tracker deal with daylight savings between the switchover (DST ends at 2:00 AM on Sunday, Nov 2nd) and the end of bus service from the previous day?
> 
> Our day changes at ~4 AM, and we run Saturday evening service on several routes until after 2 AM Sunday (Routes 31, 38, 39, and B43, that I know of).
> 
> The realtime feed renders times in ISO 8601 format (`2014-10-15T20:45:00`), but it doesn't have time zone (`2014-10-15T20:45:00-0400`) and isn't UTC (`2014-10-16T00:45:00Z`).
> 
> Will the times in the feed change along with the DST right at 2:00? Or will they remain consistent with the previous day's times until the end of service, and then change when the next day's service begins? (I assume it's the latter)

**Comment by sherson** [comment]
From Avail yesterday:

> At this point, it has been logged into the engineering cases, but no work has been scheduled yet.  The next step here is to schedule a review of the issue details with the necessary staff.

**Comment by sherson** [comment]
We talked about it again during today's conference call and the status of the issue hasn't changed. So at this point I don't see it getting fixed in time for the Spring forward switchover on 2015-03-08.

**Comment by dfaulken** [comment]
:100:

**Comment by sherson** [comment]
I brought this up yesterday and emailed Andrew Kissel <amk@availtec.com> about it.

**Comment by dfaulken** [comment]
Just to confirm here in the public repo, this is still an issue. No movement has been made on fixing the endpoint.

**Comment by bcspragu** [comment]
This thread is thoroughly entertaining. :popcorn:

**Comment by sherson** [comment]
To address this, Avail has added additional `LocalTime` fields, which went live last Sunday. For example, from https://bustracker.pvta.com/InfoPoint/rest/StopDepartures/Get/63

```
          {
            "EDT": "/Date(1518637623000-0500)/",
            "SDT": "/Date(1518637623000-0500)/",
            "ADT": null,
            "ATA": null,
            "ETA": "/Date(1518637623000-0500)/",
            "STA": "/Date(1518637623000-0500)/",
            "EDTLocalTime": "2018-47-14T02:47:03",
            "SDTLocalTime": "2018-47-14T02:47:03",
            "ADTLocalTime": null,
            "ATALocalTime": null,
            "ETALocalTime": "2018-47-14T02:47:03",
            "STALocalTime": "2018-47-14T02:47:03",
            "Dev": "00:00:00",
            "Trip": {
              "TripId": 1430,
              "RunId": 331,
              "BlockFareboxId": 331,
              "TripRecordId": 42025,
              "RunRecordId": 0,
              "BlockRecordId": 80,
              "ServiceLevelRecordId": 81,
              "StopSequence": 1023,
              "PatternRecordId": 2676,
              "TripStartTime": "/Date(1136143800000-0500)/",
              "TripStartTimeLocalTime": "2006-30-01T02:30:00",
              "InternalSignDesc": "33 Puffers Pond",
              "InternetServiceDesc": "Puffers Pond",
              "IVRServiceDesc": "Puffers Pond",
              "TripDirection": "N"
            },
            "LastUpdatedLocalTime": "2018-18-14T02:18:52",
            "LastUpdated": "/Date(1518635932680-0500)/",
            "Bay": null
          }
```

However, they're currently 12 hour clock. We've asked that they use 24 hour clock.

**Comment by sherson** [comment]
It's going to be 24 hour clock:

 ![LocalTime 24 hour clock](https://user-images.githubusercontent.com/409008/36868117-58eb4f46-1d65-11e8-928e-9a4f9dc3084b.png)

Avail said that new build passed testing; we're now just waiting to hear back about when it will be deployed (it should be before the DST switchover on 3/11).

**Comment by sherson** [comment]
24 hour clock fix been deployed.

**Comment by dfaulken** [comment]
What will the behavior of these `LocalTime` fields be during a time change?

**Comment by sherson** [comment]
^ didn't see your question here, but I replied in #76
